name: ConfigurationServerCI

on: 
  push:
    branches: 
      - master

jobs:
  first:
    name: first
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: GitHub Action for Maven
        uses: LucaFeger/action-maven-cli@1.1.0
 
